/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MappingsRouteImport } from './routes/mappings'
import { Route as TrafficRouteImport } from './routes/traffic'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsRoute = MappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRoute
  '/audit': typeof AuditRoute
  '/deploy': typeof DeployRoute
  '/login': typeof LoginRoute
  '/mappings': typeof MappingsRoute
  '/traffic': typeof TrafficRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nodes': typeof NodesRoute
  '/audit': typeof AuditRoute
  '/deploy': typeof DeployRoute
  '/login': typeof LoginRoute
  '/mappings': typeof MappingsRoute
  '/traffic': typeof TrafficRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nodes': typeof NodesRoute
  '/audit': typeof AuditRoute
  '/deploy': typeof DeployRoute
  '/login': typeof LoginRoute
  '/mappings': typeof MappingsRoute
  '/traffic': typeof TrafficRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nodes'
    | '/audit'
    | '/deploy'
    | '/login'
    | '/mappings'
    | '/traffic'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nodes'
    | '/audit'
    | '/deploy'
    | '/login'
    | '/mappings'
    | '/traffic'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/nodes'
    | '/audit'
    | '/deploy'
    | '/login'
    | '/mappings'
    | '/traffic'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NodesRoute: typeof NodesRoute
  AuditRoute: typeof AuditRoute
  DeployRoute: typeof DeployRoute
  LoginRoute: typeof LoginRoute
  MappingsRoute: typeof MappingsRoute
  TrafficRoute: typeof TrafficRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NodesRoute: NodesRoute,
  AuditRoute: AuditRoute,
  DeployRoute: DeployRoute,
  LoginRoute: LoginRoute,
  MappingsRoute: MappingsRoute,
  TrafficRoute: TrafficRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
